# This workflow will do a clean install of node dependencies, build and lint the source code and and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build-test

on: [push, pull_request]

jobs:
  test-and-build:
    name: 'Test and build'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js v.12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies and build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - name: Upload coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
