# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-build:
    name: 'Test and build'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js v.12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies and build
        run: npm ci
      - name: Test
        run: npm run test
      - name: Upload artifactory
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: ./coverage
  codecov:
    name: 'Upload coverage'
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifactory
        uses: actions/download-artifact@v1
        with:
          name: coverage
          path: ./coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          file: coverage/coverage-final.json
          flags: unittests
